version: "3.9"

services:
  usuario:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-usuario
    restart: unless-stopped

    ports:
      - "9501:9501"

    environment:
      PORT:     9501
      NODE_ENV: production
      
      # Autenticação Universal do Infisical (Machine Identity)
      CLIENT_ID:            ${CLIENT_ID:-3dcf22f2-e6a1-40c3-b3ec-2d553fd42620}
      CLIENT_SECRET:        ${CLIENT_SECRET:-ccab5e06840ed91b218513a3e5cf450999ff52e0d1e98719edd199853b3f48a8}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID:-6c550174-d6d5-4d43-a092-b077a62467dd}
      INFISICAL_ENV:        ${INFISICAL_ENV:-dev}

      # Banco de dados — vem do Infisical em produção
      DATABASE_URL: ${DATABASE_URL}

      # RabbitMQ
      RABBITMQ_URL:             ${RABBITMQ_URL:-amqp://admin:admin@academico3.rj.senac.br:5672}
      RABBITMQ_RECONNECT_DELAY: ${RABBITMQ_RECONNECT_DELAY:-5000}

    networks:
      - biblioteca-net

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  biblioteca-net:
    name: biblioteca-net
    driver: bridge